language: python
python:
  - "3.6"

install:
  - pip install -U pip pipenv virtualenv
  - pipenv install

before_script:
  - . ./local.sh && . ./secrets/.secrets && pipenv run python generate_funding_address.py

script:
  - make test
